spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Yekaterinburg
    username: chat_user
    password: chat_user
  jpa:
    show-sql: true
build:
  version: @project.version@
